apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: venuzs/frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_IP
          value: "54.159.32.238"